[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

# Uncomment if you need environment-specific settings
# [context.production]
# [context.deploy-preview]
# [context.branch-deploy]

# Redirects for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 