CREATE TABLE builds (
    id bigint primary key generated always as identity,
    email text,
    custo DECIMAL(10, 2),
    preco DECIMAL(10, 2),
    tag_modelo text,
    tag_specs text,
    ziplock BOOLEAN,
    certificado BOOLEAN,
    porta_certificado BOOLEAN,
    marca_pagina BOOLEAN,
    chave_allen_25mm BOOLEAN,
    roldana BOOLEAN,
    feltro BOOLEAN,
    ferrules BOOLEAN,
    tensor BOOLEAN,
    jack_plate BOOLEAN,
    treble_bleed BOOLEAN,
    jack text,
    strings text,
    scale_length DECIMAL(5, 2),
    case_type text,
    body_color text,
    body_wood text,
    top_wood text,
    top_color text,
    burst text,
    top_coat text,
    neck_wood text,
    fretboard_wood text,
    inlays text,
    nut text,
    frets INT,
    neck_construction text,
    side_dots BOOLEAN,
    neck_reinforcements text,
    neck_profile text,
    fretboard_radius DECIMAL(5, 2),
    headstock_angle DECIMAL(4, 2),
    bridge text,
    tuners text,
    hardware_color text,
    pickups text,
    knobs text,
    switch text,
    pickups_finish text,
    pickups_customization text,
    plates text
);