DELETE FROM options;

INSERT INTO options (id_related_subcategory, id, active, is_default, option, front_image_url, back_image_url, zindex, view, price_usd, scale_length, color_hardware, strings)
VALUES
('1', 699, 'true', 'true', 'Base specs', NULL, NULL, '999', NULL, '1739', 'all', NULL, 'all'),
('3', 369, 'true', 'true', '6 Strings', 'omni-cordas-6.png', NULL, '30', 'front', '8', 'all', NULL, NULL),
('3', 370, 'true', 'false', '7 Strings', 'omni-cordas-6.png', NULL, '30', 'front', '17', 'all', NULL, NULL),
('4', 242, 'true', 'true', '25,5"', NULL, NULL, NULL, NULL, '0', NULL, NULL, 'all'),
('4', 243, 'true', 'false', '25,5" - 27" (Multiscale)', NULL, NULL, NULL, NULL, '43', NULL, NULL, 'all'),
('5', 1030, 'true', 'false', 'Spokewheel', 'omni-spokewheel-preto.png', NULL, '7', 'front', '0', 'all', 'Preto', 'all'),
('5', 1031, 'true', 'false', 'Spokewheel', 'omni-spokewheel-cromado.png', NULL, '7', 'front', '0', 'all', 'Cromado', 'all'),
('39', 716, 'true', 'false', 'Blue', 'omni-tampo-buckeye-burl-azul.png', NULL, '3', 'front', '0', 'all', NULL, 'all'),
('39', 1017, 'true', 'true', 'Natural', 'omni-tampo-buckeye-burl-natural.png', NULL, '3', 'front', '0', 'all', NULL, 'all'),
('39', 718, 'true', 'false', 'Red', 'omni-tampo-buckeye-burl-vermelho.png', NULL, '3', 'front', '0', 'all', NULL, 'all'),
('39', 719, 'true', 'false', 'Yellow', 'omni-tampo-buckeye-burl-amarelo.png', NULL, '3', 'front', '0', 'all', NULL, 'all'),
('39', 720, 'true', 'false', 'Purple', 'omni-tampo-buckeye-burl-roxo.png', NULL, '3', 'front', '0', 'all', NULL, 'all'),
('40', 734, 'true', 'false', 'Blue  ', 'omni-tampo-flamed-maple-azul.png', NULL, '3', 'all', '0', 'all', NULL, 'all'),
('40', 1120, 'true', 'false', 'Green  ', 'omni-tampo-flamed-maple-verde.png', NULL, '3', 'all', '0', 'all', NULL, 'all'),
('40', 1119, 'true', 'false', 'Gray  ', 'omni-tampo-flamed-maple-cinza.png', NULL, '3', 'all', '0', 'all', NULL, 'all'),
('40', 1121, 'true', 'false', 'Orange', 'omni-tampo-flamed-maple-laranja.png', NULL, '3', 'all', '0', 'all', NULL, 'all'),
('40', 735, 'true', 'true', 'Natural  ', 'omni-tampo-flamed-maple.png', NULL, '3', 'all', '0', 'all', NULL, 'all'),
('40', 736, 'true', 'false', 'Red', 'omni-tampo-flamed-maple-vermelho.png', NULL, '3', 'all', '0', 'all', NULL, 'all'),
('40', 1122, 'true', 'false', 'Black', 'omni-tampo-flamed-maple-preto.png', NULL, '3', 'all', '0', 'all', NULL, 'all'),
('40', 738, 'true', 'false', 'Purple', 'omni-tampo-flamed-maple-roxo.png', NULL, '3', 'all', '0', 'all', NULL, 'all'),
('41', 1019, 'true', 'true', 'Natural', 'omni-tampo-maple-burl.png', NULL, '3', 'all', '0', 'all', NULL, 'all'),
('41', 1021, 'true', 'false', 'Blue', 'omni-tampo-maple-burl-azul.png', NULL, '3', 'all', '0', 'all', NULL, 'all'),
('41', 1023, 'true', 'false', 'Red', 'omni-tampo-maple-burl-vermelho.png', NULL, '3', 'all', '0', 'all', NULL, 'all'),
('41', 1022, 'true', 'false', 'Yellow', 'omni-tampo-maple-burl-amarelo.png', NULL, '3', 'all', '0', 'all', NULL, 'all'),
('41', 1020, 'true', 'false', 'Purple', 'omni-tampo-maple-burl-roxo.png', NULL, '3', 'all', '0', 'all', NULL, 'all'),
('41', 1125, 'true', 'false', 'Black', 'omni-tampo-maple-burl-preto.png', NULL, '3', 'all', '0', 'all', NULL, 'all'),
('44', 1024, 'true', 'true', 'Natural', 'omni-tampo-quilted-maple.png', NULL, '3', 'all', '0', 'all', NULL, 'all'),
('44', 1025, 'true', 'false', 'Blue', 'omni-tampo-quilted-maple-azul.png', NULL, '3', 'all', '0', 'all', NULL, 'all'),
('44', 1026, 'true', 'false', 'Red', 'omni-tampo-quilted-maple-vermelho.png', NULL, '3', 'all', '0', 'all', NULL, 'all'),
('44', 1113, 'true', 'false', 'Green', 'omni-tampo-quilted-maple-verde.png', NULL, '3', 'all', '0', 'all', NULL, 'all'),
('44', 1115, 'true', 'false', 'Orange', 'omni-tampo-quilted-maple-laranja.png', NULL, '3', 'all', '0', 'all', NULL, 'all'),
('44', 1114, 'true', 'false', 'Gray', 'omni-tampo-quilted-maple-cinza.png', NULL, '3', 'all', '0', 'all', NULL, 'all'),
('44', 1117, 'true', 'false', 'Black', 'omni-tampo-quilted-maple-preto.png', NULL, '3', 'all', '0', 'all', NULL, 'all'),
('44', 1118, 'true', 'false', 'Dark Green', 'omni-tampo-quilted-maple-verde-escuro.png', NULL, '3', 'all', '0', 'all', NULL, 'all'),
('44', 1028, 'true', 'false', 'Purple', 'omni-tampo-quilted-maple-roxo.png', NULL, '3', 'all', '0', 'all', NULL, 'all'),
('6', 729, 'true', 'true', 'Bolt-on', NULL, 'omni-braco-bolts-preto-verso.png', '10', 'back', '0', 'all', 'Preto', 'all'),
('6', 1152, 'true', 'false', 'Bolt-on', NULL, 'omni-braco-bolts-cromado-verso.png', '10', 'back', '0', 'all', 'Cromado', 'all'),
('6', 21, 'true', 'false', 'Set', NULL, NULL, NULL, 'back', '31', 'all', NULL, 'all'),
('7', 83, 'true', 'false', '1 pc - Pau Ferro  ', 'omni-braco-pau-ferro.png', 'omni-braco-pau-ferro-verso.png', '5', 'both', '77', 'all', NULL, '6'),
('7', 1151, 'true', 'true', '1 pc - Pau Ferro (Darkened)', 'omni-braco-pau-ferro-escuro.png', 'omni-braco-pau-ferro-escuro-verso.png', '5', 'both', '81', 'all', NULL, '6'),
('7', 989, 'true', 'false', '1 pc - Pau Ferro  ', NULL, NULL, '5', 'front', '101', 'all', NULL, '7'),
('7', 86, 'true', 'false', '1 pc - Flamed Maple  ', 'omni-braco-flamed-maple.png', 'omni-braco-flamed-maple-verso.png', '5', 'both', '106', 'all', NULL, '6'),
('7', 982, 'true', 'false', '1 pc - Flamed Maple  ', NULL, NULL, '5', 'front', '137', 'all', NULL, '7'),
('8', 71, 'true', 'true', 'Pau Ferro', 'omni-escala-pau-ferro.png', NULL, '6', 'front', '29', 'all', NULL, '6'),
('8', 72, 'true', 'false', 'Pau Ferro 7', NULL, NULL, '6', 'front', '50', 'all', NULL, '7'),
('8', 74, 'true', 'false', 'Flamed Maple', 'omni-escala-flamed-maple.png', NULL, '6', 'front', '43', 'all', NULL, '6'),
('8', 747, 'true', 'false', 'Flamed Maple ', NULL, NULL, '6', 'front', '69', 'all', NULL, '7'),
('8', 76, 'true', 'false', 'Pale Moon Ebony  ', 'omni-escala-pale-moon.png', NULL, '6', 'front', '157', 'all', NULL, '6'),
('8', 751, 'true', 'false', 'Pale Moon Ebony', NULL, NULL, '6', 'front', '249', 'all', NULL, '7'),
('9', 428, 'true', 'false', '12"', NULL, NULL, NULL, NULL, '0', 'all', NULL, 'all'),
('9', 431, 'true', 'false', '14"', NULL, NULL, NULL, NULL, '0', 'all', NULL, 'all'),
('9', 430, 'true', 'true', '16"', NULL, NULL, NULL, NULL, '0', 'all', NULL, 'all'),
('9', 429, 'true', 'false', '20"', NULL, NULL, NULL, NULL, '0', 'all', NULL, 'all'),
('10', 466, 'true', 'true', 'C-Thin', NULL, NULL, NULL, NULL, '0', 'all', NULL, 'all'),
('10', 467, 'true', 'false', 'D  ', NULL, NULL, NULL, NULL, '0', 'all', NULL, 'all'),
('11', 440, 'true', 'true', 'Carbon fiber', NULL, NULL, NULL, NULL, '27', 'all', NULL, 'all'),
('12', 393, 'true', 'true', 'Graphtech TUSQ', NULL, NULL, '7', NULL, '9', 'all', NULL, 'all'),
('13', 405, 'true', 'true', 'None', NULL, NULL, '10', 'front', '0', 'all', NULL, 'all'),
('14', 179, 'true', 'true', 'Jescar Stainless Steel (Jumbo)  ', 'omni-braco-trastes-padrao.png', NULL, '8', 'front', '31', 'all', NULL, 'all'),
('14', 396, 'true', 'false', 'Jescar Stainless Steel (Extra Jumbo)  ', 'omni-braco-trastes-padrao.png', NULL, '8', 'front', '31', 'all', NULL, 'all'),
('15', 404, 'true', 'true', 'None', NULL, NULL, '7', 'front', '0', 'all', NULL, 'all'),
('15', 754, 'true', 'false', 'Constellations - Black  ', 'omni-braco-inlays-constelacoes-preto.png', NULL, '7', 'front', '0', 'all', NULL, 'all'),
('15', 1004, 'true', 'false', 'Constellations - White  ', 'omni-braco-inlays-constelacoes-branco.png', NULL, '7', 'front', '0', 'all', NULL, 'all'),
('17', 425, 'true', 'true', 'Standard  ', NULL, NULL, NULL, NULL, '0', 'all', NULL, 'all'),
('17', 426, 'true', 'false', 'Fluorescent (Green)', NULL, NULL, NULL, NULL, '53', 'all', NULL, 'all'),
('18', 456, 'true', 'true', 'Matte', NULL, NULL, NULL, NULL, '0', 'all', NULL, 'all'),
('18', 457, 'true', 'false', 'Gloss', NULL, NULL, NULL, NULL, '0', 'all', NULL, 'all'),
('50', 1130, 'true', 'true', 'None', NULL, NULL, '4', 'front', '0', 'all', NULL, 'all'),
('50', 1132, 'true', 'false', 'Purple', 'omni-burst-glow-invertido-roxo.png', NULL, '4', 'front', '0', 'all', NULL, 'all'),
('50', 1133, 'true', 'false', 'Red', 'omni-burst-glow-invertido-vermelho.png', NULL, '4', 'front', '0', 'all', NULL, 'all'),
('50', 1134, 'true', 'false', 'Black', 'omni-burst-glow-invertido-preto.png', NULL, '4', 'front', '0', 'all', NULL, 'all'),
('50', 1137, 'true', 'false', 'Blue', 'omni-burst-glow-invertido-azul.png', NULL, '4', 'front', '0', 'all', NULL, 'all'),
('50', 1142, 'true', 'false', 'Gradient - Blue', 'omni-burst-glow-degrade-azul.png', NULL, '4', 'front', '0', 'all', NULL, 'all'),
('50', 1143, 'true', 'false', 'Gradient - Black', 'omni-burst-glow-degrade-preto.png', NULL, '4', 'front', '0', 'all', NULL, 'all'),
('50', 1145, 'true', 'false', 'Gradient - Purple', 'omni-burst-glow-degrade-roxo.png', NULL, '4', 'front', '0', 'all', NULL, 'all'),
('50', 1144, 'true', 'false', 'Gradient - Green', 'omni-burst-glow-degrade-verde.png', NULL, '4', 'front', '0', 'all', NULL, 'all'),
('19', 91, 'true', 'true', 'Paulownia', NULL, NULL, '1', 'front', '29', 'all', NULL, 'all'),
('19', 94, 'true', 'false', 'Mahogany', 'omni-corpo-mogno.png', 'omni-corpo-mogno-verso.png', '1', 'front', '49', 'all', NULL, 'all'),
('19', 274, 'true', 'false', 'Freijó', NULL, NULL, '1', 'front', '60', 'all', NULL, 'all'),
('46', 1032, 'true', 'true', 'Natural', 'omni-corpo-paulownia.png', 'omni-corpo-paulownia-verso.png', '1', 'front', '0', 'all', NULL, 'all'),
('46', 1033, 'true', 'false', 'Translucent Yellow', 'omni-corpo-paulownia-amarelo.png', 'omni-corpo-paulownia-amarelo-verso.png', '2', 'front', '0', 'all', NULL, 'all'),
('46', 1034, 'true', 'false', 'Translucent Red', 'omni-corpo-paulownia-vermelho.png', 'omni-corpo-paulownia-vermelho-verso.png', '2', 'front', '0', 'all', NULL, 'all'),
('46', 1035, 'true', 'false', 'Translucent Green', 'omni-corpo-paulownia-verde.png', 'omni-corpo-paulownia-verde-verso.png', '2', 'front', '0', 'all', NULL, 'all'),
('46', 1036, 'true', 'false', 'Translucent Purple', 'omni-corpo-paulownia-roxo.png', 'omni-corpo-paulownia-roxo-verso.png', '2', 'front', '0', 'all', NULL, 'all'),
('46', 1038, 'true', 'false', 'Translucent Black', 'omni-corpo-paulownia-preto.png', 'omni-corpo-paulownia-preto-verso.png', '2', 'front', '0', 'all', NULL, 'all'),
('46', 1123, 'true', 'false', 'Translucent Gray', 'omni-corpo-paulownia-cinza.png', 'omni-corpo-paulownia-cinza-verso.png', '2', 'front', '0', 'all', NULL, 'all'),
('46', 1047, 'true', 'false', 'White', 'omni-corpo-branco.png', 'omni-corpo-branco-verso.png', '3', 'front', '0', 'all', NULL, 'all'),
('46', 1048, 'true', 'false', 'Neon Yellow', 'omni-corpo-amarelo-neon.png', 'omni-corpo-amarelo-neon-verso.png', '3', 'front', '0', 'all', NULL, 'all'),
('46', 1049, 'true', 'false', 'Yellow', 'omni-corpo-amarelo.png', 'omni-corpo-amarelo-verso.png', '3', 'front', '0', 'all', NULL, 'all'),
('46', 1050, 'true', 'false', 'Neon Blue', 'omni-corpo-azul-neon.png', 'omni-corpo-azul-neon-verso.png', '3', 'front', '0', 'all', NULL, 'all'),
('46', 1051, 'true', 'false', 'Blue', 'omni-corpo-azul.png', 'omni-corpo-azul-verso.png', '3', 'front', '0', 'all', NULL, 'all'),
('46', 1052, 'true', 'false', 'Gray', 'omni-corpo-cinza.png', 'omni-corpo-cinza-verso.png', '3', 'front', '0', 'all', NULL, 'all'),
('46', 1053, 'true', 'false', 'Neon Orange', 'omni-corpo-laranja-neon.png', 'omni-corpo-laranja-neon-verso.png', '3', 'front', '0', 'all', NULL, 'all'),
('46', 1054, 'true', 'false', 'Black', 'omni-corpo-preto.png', 'omni-corpo-preto-verso.png', '3', 'front', '0', 'all', NULL, 'all'),
('46', 1055, 'true', 'false', 'Neon Pink', 'omni-corpo-rosa-neon.png', 'omni-corpo-rosa-neon-verso.png', '3', 'front', '0', 'all', NULL, 'all'),
('46', 1056, 'true', 'false', 'Pink', 'omni-corpo-rosa.png', 'omni-corpo-rosa-verso.png', '3', 'front', '0', 'all', NULL, 'all'),
('46', 1057, 'true', 'false', 'Green', 'omni-corpo-verde.png', 'omni-corpo-verde-verso.png', '3', 'front', '0', 'all', NULL, 'all'),
('46', 1124, 'true', 'false', 'Black Sparkle', 'omni-corpo-preto-sparkle.png', 'omni-corpo-preto-sparkle-verso.png', '3', 'front', '0', 'all', NULL, 'all'),
('47', 1039, 'true', 'true', 'Natural', 'omni-corpo-freijo.png', 'omni-corpo-freijo-verso.png', '1', 'front', '0', 'all', NULL, 'all'),
('47', 1041, 'true', 'false', 'Translucent Red', 'omni-corpo-freijo-vermelho.png', 'omni-corpo-freijo-vermelho-verso.png', '2', 'front', '0', 'all', NULL, 'all'),
('47', 1042, 'true', 'false', 'Translucent Purple', 'omni-corpo-freijo-roxo.png', 'omni-corpo-freijo-roxo-verso.png', '2', 'front', '0', 'all', NULL, 'all'),
('47', 1043, 'true', 'false', 'Translucent Green', 'omni-corpo-freijo-verde.png', 'omni-corpo-freijo-verde-verso.png', '2', 'front', '0', 'all', NULL, 'all'),
('47', 1040, 'true', 'false', 'Translucent Black', 'omni-corpo-freijo-preto.png', 'omni-corpo-freijo-preto-verso.png', '2', 'front', '0', 'all', NULL, 'all'),
('47', 1102, 'true', 'false', 'White', 'omni-corpo-branco.png', 'omni-corpo-branco-verso.png', '3', 'front', '0', 'all', NULL, 'all'),
('47', 1103, 'true', 'false', 'Neon Yellow', 'omni-corpo-amarelo-neon.png', 'omni-corpo-amarelo-neon-verso.png', '3', 'front', '0', 'all', NULL, 'all'),
('47', 1104, 'true', 'false', 'Yellow', 'omni-corpo-amarelo.png', 'omni-corpo-amarelo-verso.png', '3', 'front', '0', 'all', NULL, 'all'),
('47', 1105, 'true', 'false', 'Neon Blue', 'omni-corpo-azul-neon.png', 'omni-corpo-azul-neon-verso.png', '3', 'front', '0', 'all', NULL, 'all'),
('47', 1106, 'true', 'false', 'Blue', 'omni-corpo-azul.png', 'omni-corpo-azul-verso.png', '3', 'front', '0', 'all', NULL, 'all'),
('47', 1107, 'true', 'false', 'Gray', 'omni-corpo-cinza.png', 'omni-corpo-cinza-verso.png', '3', 'front', '0', 'all', NULL, 'all'),
('47', 1108, 'true', 'false', 'Neon Orange', 'omni-corpo-laranja-neon.png', 'omni-corpo-laranja-neon-verso.png', '3', 'front', '0', 'all', NULL, 'all'),
('47', 1109, 'true', 'false', 'Black', 'omni-corpo-preto.png', 'omni-corpo-preto-verso.png', '3', 'front', '0', 'all', NULL, 'all'),
('47', 1110, 'true', 'false', 'Neon Pink', 'omni-corpo-rosa-neon.png', 'omni-corpo-rosa-neon-verso.png', '3', 'front', '0', 'all', NULL, 'all'),
('47', 1111, 'true', 'false', 'Pink', 'omni-corpo-rosa.png', 'omni-corpo-rosa-verso.png', '3', 'front', '0', 'all', NULL, 'all'),
('47', 1112, 'true', 'false', 'Green', 'omni-corpo-verde.png', 'omni-corpo-verde-verso.png', '3', 'front', '0', 'all', NULL, 'all'),
('21', 244, 'true', 'false', 'Flamed Maple', NULL, NULL, '3', 'front', '145', 'all', NULL, 'all'),
('21', 1045, 'true', 'true', 'None', NULL, NULL, '3', 'front', '0', 'all', NULL, 'all'),
('21', 53, 'true', 'false', 'Maple Burl  ', NULL, NULL, '3', 'front', '279', 'all', NULL, 'all'),
('21', 54, 'true', 'false', 'Golden Camphor', 'omni-tampo-golden-camphor.png', NULL, '3', 'front', '279', 'all', NULL, 'all'),
('21', 55, 'true', 'false', 'Buckeye Burl', NULL, NULL, '3', 'front', '365', 'all', NULL, 'all'),
('21', 59, 'true', 'false', 'Quilted Maple', NULL, NULL, '3', 'front', '329', 'all', NULL, 'all'),
('21', 62, 'true', 'false', 'Hybrid (Burl & Resin)  ', 'omni-tampo-hibrido.png', NULL, '3', 'front', '711', 'all', NULL, 'all'),
('21', 64, 'true', 'false', 'Koa  ', 'omni-tampo-koa.png', NULL, '3', 'front', '1148', 'all', NULL, 'all'),
('21', 65, 'true', 'false', 'Mun Ebony  ', 'omni-tampo-mun-ebony.png', NULL, '3', 'front', '1018', 'all', NULL, 'all'),
('23', 409, 'true', 'true', 'Acrylic  ', NULL, 'omni-plates-fixa-preto.png', NULL, 'back', '10', 'all', NULL, 'all'),
('23', 1153, 'true', 'false', 'Acrylic  ', NULL, 'omni-plates-tremolo-preto.png', NULL, 'back', '10', 'all', NULL, 'all'),
('23', 1156, 'true', 'false', 'Acrylic  ', NULL, 'omni-plates-multiscale-preto.png', NULL, 'back', '10', 'all', NULL, 'all'),
('23', 408, 'true', 'false', 'Wood  ', NULL, NULL, NULL, 'back', '12', 'all', NULL, 'all'),
('24', 230, 'true', 'true', 'Straight', NULL, NULL, NULL, NULL, '0', 'all', NULL, 'all'),
('24', 229, 'true', 'false', 'Angled (10º)  ', NULL, NULL, NULL, NULL, '133', 'all', NULL, 'all'),
('25', 727, 'true', 'true', 'Black', NULL, NULL, NULL, NULL, '0', 'all', NULL, 'all'),
('25', 728, 'true', 'false', 'Chrome', NULL, NULL, NULL, NULL, '0', 'all', NULL, 'all'),
('26', 112, 'true', 'true', 'Hipshot Bridge', 'omni-ponte-fixa-6-preto.png', NULL, '5', 'front', '110', 'standard', 'Preto', '6'),
('26', 996, 'true', 'false', 'Hipshot Bridge', 'omni-ponte-fixa-6-cromado.png', NULL, '5', 'front', '110', 'standard', 'Cromado', '6'),
('26', 116, 'true', 'false', 'Evertune Bridge', NULL, NULL, '5', 'front', '394', 'standard', 'Preto', '6'),
('26', 120, 'true', 'false', 'Multiscale Hipshot Bridge', 'omni-ponte-fixa-6-preto.png', NULL, '5', 'front', '155', 'multiscale', 'Preto', '7'),
('26', 122, 'true', 'false', 'Multiscale Hipshot Bridge', 'omni-ponte-fixa-6-cromado.png', NULL, '5', 'front', '192', 'multiscale', 'Cromado', '7'),
('26', 390, 'true', 'false', 'Vega-trem Tremolo', NULL, NULL, '5', 'front', '369', 'standard', 'Preto', '6'),
('26', 128, 'true', 'false', 'Gotoh 510 Tremolo', NULL, NULL, '5', 'front', '84', 'standard', 'Preto', '6'),
('26', 130, 'true', 'false', 'Gotoh Floating (Floyd Rose)', NULL, NULL, '5', 'front', '197', 'standard', 'Preto', '6'),
('27', 98, 'true', 'false', 'Gotoh SG381 (Locking)', 'omni-tarraxas-6-cromado.png', 'omni-tarraxas-cromado-verso.png', '10', 'front', '77', 'all', 'Cromado', '6'),
('27', 1100, 'true', 'true', 'Gotoh SG381 (Locking)', 'omni-tarraxas-6-preto.png', 'omni-tarraxas-preto-verso.png', '10', 'front', '77', 'all', 'Preto', '6'),
('27', 99, 'true', 'false', 'Gotoh SG381 (7-string)', 'omni-tarraxas-6-preto.png', 'omni-tarraxas-preto-verso.png', '10', 'front', '116', 'all', 'Preto', '7'),
('27', 102, 'true', 'false', 'Hipshot Grip-lock Open (Locking)', 'omni-tarraxas-6-preto.png', 'omni-tarraxas-preto-verso.png', '10', 'front', '109', 'all', 'Preto', '6'),
('27', 997, 'true', 'false', 'Hipshot Grip-lock Open (Locking)', 'omni-tarraxas-6-cromado.png', 'omni-tarraxas-cromado-verso.png', '10', 'front', '109', 'all', 'Cromado', '6'),
('27', 104, 'true', 'false', 'Hipshot Grip-lock Open (Locking)', NULL, NULL, '10', 'front', '164', 'all', 'Preto', '7'),
('27', 1015, 'true', 'false', 'Hipshot Grip-lock Open (Locking)', NULL, NULL, '10', 'front', '164', 'all', 'Cromado', '7'),
('28', 36, 'true', 'false', 'Wooden Tuners (6x)', NULL, NULL, '10', 'front', '232', 'all', NULL, '6'),
('29', 731, 'true', 'false', 'Volume  ', 'omni-knob-volume-preto.png', NULL, '5', 'front', '23', 'all', 'Preto', 'all'),
('29', 999, 'true', 'false', 'Volume  ', 'omni-knob-volume-cromado.png', NULL, '5', 'front', '23', 'all', 'Cromado', 'all'),
('29', 1011, 'true', 'true', 'Volume + Tone', 'omni-knobs-preto.png', NULL, '5', 'front', '43', 'all', 'Preto', 'all'),
('29', 1012, 'true', 'false', 'Volume + Tone', 'omni-knobs-cromado.png', NULL, '5', 'front', '43', 'all', 'Cromado', 'all'),
('38', 195, 'true', 'true', '5-way Oak Grigsby', 'omni-switch-blade.png', NULL, '5', 'front', '26', 'all', NULL, 'all'),
('30', 147, 'true', 'false', 'Fishman Modern', NULL, NULL, '4', 'front', '301', 'all', NULL, '6'),
('30', 1094, 'true', 'false', 'Pluria Vintage', NULL, NULL, '4', 'front', '82', 'all', NULL, '6'),
('30', 1095, 'true', 'true', 'Pluria Modern', NULL, NULL, '4', 'front', '82', 'all', NULL, '6'),
('30', 148, 'true', 'false', 'Fishman Modern', NULL, NULL, '4', 'front', '224', 'all', NULL, '7'),
('30', 1096, 'true', 'true', 'Pluria Modern', NULL, NULL, '4', 'front', '106', 'all', NULL, '7'),
('30', 1098, 'true', 'false', 'Pluria Vintage', NULL, NULL, '4', 'front', '106', 'all', NULL, '7'),
('30', 1097, 'true', 'false', 'Pluria Modern (Multiscale)', NULL, NULL, '4', 'front', '170', 'multiscale', NULL, '7'),
('30', 149, 'true', 'false', 'Fishman Modern (Soapbar)', NULL, NULL, '4', 'front', '215', 'all', NULL, '7'),
('30', 151, 'true', 'false', 'Fishman Abasi', NULL, NULL, '4', 'front', '352', 'all', NULL, '6'),
('30', 152, 'true', 'false', 'Fishman Abasi', NULL, NULL, '4', 'front', '266', 'all', NULL, '7'),
('30', 153, 'true', 'false', 'Fishman Abasi (Soapbar)', NULL, NULL, '4', 'front', '273', 'all', NULL, '7'),
('30', 1085, 'true', 'false', 'None', NULL, NULL, '4', 'front', '0', 'all', NULL, '6'),
('30', 1093, 'true', 'false', 'None', NULL, NULL, '4', 'front', '0', 'all', NULL, '7'),
('30', 1062, 'true', 'false', 'Bare Knuckle (Any model)', NULL, NULL, NULL, 'front', '478', 'standard', NULL, '6'),
('30', 1063, 'true', 'false', 'Bare Knuckle (Any model, Multiscale)', NULL, NULL, NULL, 'front', '553', 'multiscale', NULL, '6'),
('30', 1088, 'true', 'false', 'Bare Knuckle', NULL, NULL, NULL, 'front', '650', 'standard', NULL, '7'),
('30', 1089, 'true', 'false', 'Bare Knuckle (Multiscale)', NULL, NULL, NULL, 'front', '752', 'multiscale', NULL, '7'),
('32', 755, 'true', 'true', 'Black', 'captador-humbucker-preto.png', NULL, '5', 'front', '0', 'all', NULL, '6'),
('32', 756, 'true', 'false', 'White', 'captador-humbucker-branco.png', NULL, '5', 'front', '0', 'all', NULL, '6'),
('32', 1147, 'true', 'false', 'Nickel Cover', 'captador-humbucker-capa-niquel.png', NULL, '5', 'front', '0', 'all', NULL, '6'),
('32', 1148, 'true', 'false', 'Black Cover', 'captador-humbucker-capa-preto.png', NULL, '5', 'front', '0', 'all', NULL, '6'),
('32', 1149, 'true', 'false', 'Fishman - White', 'captador-humbucker-fishman-branco.png', NULL, '5', 'front', '0', 'all', NULL, '6'),
('32', 1150, 'true', 'false', 'Fishman - Black', 'captador-humbucker-fishman-preto.png', NULL, '5', 'front', '0', 'all', NULL, '6'),
('33', 37, 'true', 'false', '1.5mm wooden toppers (2x)', NULL, NULL, '6', 'front', '95', 'all', NULL, 'all'),
('33', 1129, 'true', 'true', 'None', NULL, NULL, '6', 'front', '0', 'all', NULL, 'all'),
('36', 379, 'true', 'true', 'Soft Case', NULL, NULL, NULL, NULL, '26', 'all', NULL, 'all'),
('36', 1099, 'true', 'false', 'Hard Case', NULL, NULL, NULL, NULL, '106', 'all', NULL, 'all');

DELETE FROM subcategories;

INSERT INTO subcategories (id_related_category, id, subcategory, sort_order, hidden)
VALUES
('75', 2, 'Model', '1', 'true'),
('75', 1, 'Project', '2', NULL),
('75', 3, 'Strings', '3', NULL),
('75', 4, 'Scale Length', '4', NULL),
('75', 36, 'Case', '5', NULL),
('13', 19, 'Body Wood', '1', 'false'),
('13', 46, 'Body Color', '2', 'true'),
('13', 47, 'Body Color', '2', 'true'),
('13', 21, 'Top Wood', '4', 'false'),
('13', 39, 'Top Color', '5', 'true'),
('13', 40, 'Top Color', '5', 'true'),
('13', 41, 'Top Color', '5', 'true'),
('13', 42, 'Top Color', '5', 'true'),
('13', 43, 'Top Color', '5', 'true'),
('13', 44, 'Top Color', '5', 'true'),
('13', 45, 'Top Color', '5', 'true'),
('13', 22, 'Top Color', '5', 'true'),
('13', 50, 'Burst', '6', 'false'),
('13', 18, 'Top Coat', '7', 'false'),
('9', 7, 'Neck Wood', '1', NULL),
('9', 8, 'Fretboard Wood', '2', NULL),
('9', 15, 'Inlays', '3', NULL),
('9', 13, 'Binding', '5', 'true'),
('9', 6, 'Neck Construction', '6', NULL),
('9', 9, 'Fretboard Radius', '7', NULL),
('9', 10, 'Neck Profile', '8', NULL),
('9', 11, 'Neck Reinforcements', '9', NULL),
('9', 12, 'Nut', '10', NULL),
('9', 14, 'Frets', '11', NULL),
('9', 17, 'Side Dots', '12', NULL),
('9', 24, 'Headstock Angle', '13', NULL),
('32', 25, 'Hardware Color', '1', NULL),
('32', 26, 'Bridge', '2', NULL),
('32', 27, 'Tuners', '3', NULL),
('32', 28, 'Tuners – Customization', '4', 'true'),
('78', 30, 'Pickups', '1', NULL),
('78', 32, 'Pickups Finish', '3', NULL),
('78', 33, 'Pickups – Customization', '4', NULL),
('78', 29, 'Knobs', '7', NULL),
('78', 38, 'Switch', '7', 'false'),
('78', 23, 'Plates', '8', NULL),
('19', 5, 'IFS', '99', 'true');