DELETE FROM options;

INSERT INTO options (id_related_subcategory, id, active, is_default, option, zindex, image_url, view, strings, color_hardware, scale_length, price_usd) VALUES
(1, 699, true, true, 'Base specs', NULL, NULL, NULL, 'all', NULL, NULL, 1764),
(3, 369, true, true, '6 Strings', 30, 'omni-cordas-6.png', 'front', 'all', NULL, NULL, 8),
(3, 370, true, false, '7 Strings', 30, NULL, 'front', 'all', NULL, NULL, 17),
(4, 242, true, true, '25,5"', NULL, NULL, NULL, 'all', NULL, NULL, 0),
(4, 243, true, false, '25,5" - 27" (Multiscale)', NULL, NULL, NULL, 'all', NULL, NULL, 43),
(5, 716, false, false, 'Top - Blue Buckeye Burl', 2, 'omni-tampo-buckeye-burl-azul.png', 'front', 'all', NULL, NULL, 0),
(5, 718, false, false, 'Top - Red Buckeye Burl', 2, 'omni-tampo-buckeye-burl-vermelho.png', 'front', 'all', NULL, NULL, 0),
(5, 719, false, false, 'Top - Yellow Buckeye Burl', 2, 'omni-tampo-buckeye-burl-amarelo.png', 'front', 'all', NULL, NULL, 0),
(5, 720, false, false, 'Top - Purple Buckeye Burl', 2, 'omni-tampo-buckeye-burl-roxo.png', 'front', 'all', NULL, NULL, 0),
(5, 717, false, false, 'Headplate - Buckeye Burl', 6, 'omni-headplate-buckeye-burl.png', 'front', 'all', NULL, NULL, 0),
(5, 754, false, false, 'Inlays - Constellations - Black', 7, 'omni-braco-inlays-constelacoes-preto.png', 'front', 'all', NULL, NULL, 0),
(5, 1004, false, false, 'Inlays - Constellations - White', 7, 'omni-braco-inlays-constelacoes-branco.png', 'front', 'all', NULL, NULL, 0),
(5, 994, false, true, 'Lighting - Omni Luz', 99, 'omni-lighting-luz-corpo.png', 'front', 'all', NULL, NULL, 0),
(5, 995, false, true, 'Lighting - Omni Sombra', 99, 'omni-lighting-sombra-corpo.png', 'front', 'all', NULL, NULL, 0),
(6, 729, true, true, 'Bolt-on', NULL, NULL, 'back', 'all', NULL, NULL, 0),
(6, 21, true, false, 'Set', NULL, NULL, 'back', 'all', NULL, NULL, 31),
(7, 83, true, true, '1 pc - Pau Ferro', 5, 'omni-braco-pau-ferro.png', 'front', '6', NULL, NULL, 77),
(7, 989, true, true, '1 pc - Pau Ferro', 5, NULL, 'front', '7', NULL, NULL, 101),
(7, 86, true, false, '1 pc - Flamed Maple', 5, NULL, 'front', '6', NULL, NULL, 106),
(7, 982, true, false, '1 pc - Flamed Maple', 5, NULL, 'front', '7', NULL, NULL, 137),
(7, 87, false, false, '1 pc - Roasted Flamed Maple', 5, NULL, 'front', '6', NULL, NULL, 114),
(7, 983, false, false, '1 pc - Roasted Flamed Maple', 5, NULL, 'front', '7', NULL, NULL, 148),
(7, 246, false, false, '5 pc - Pau Ferro + Purpleheart', 5, NULL, 'front', '6', NULL, NULL, 108),
(7, 984, false, false, '5 pc - Pau Ferro + Purpleheart', 5, NULL, 'front', '7', NULL, NULL, 141),
(7, 247, false, false, '5 pc - Pau Ferro + Ivory', 5, NULL, 'front', '6', NULL, NULL, 108),
(7, 985, false, false, '5 pc - Pau Ferro + Ivory', 5, NULL, 'front', '7', NULL, NULL, 141),
(7, 248, false, false, '5 pc - Flamed Maple + Purpleheart', 5, NULL, 'front', '6', NULL, NULL, 136),
(7, 986, false, false, '5 pc - Flamed Maple + Purpleheart', 5, NULL, 'front', '7', NULL, NULL, 177),
(7, 88, false, false, '9 pc - Walnut + Purpleheart + Ivory', 5, NULL, 'front', '6', NULL, NULL, 172),
(7, 987, false, false, '9 pc - Walnut + Purpleheart + Ivory', 5, NULL, 'front', '7', NULL, NULL, 223),
(7, 89, false, false, '9 pc - Pau Ferro + Purpleheart + Ivory', 5, NULL, 'front', '6', NULL, NULL, 215),
(7, 988, false, false, '9 pc - Pau Ferro + Purpleheart + Ivory', 5, NULL, 'front', '7', NULL, NULL, 280),
(8, 71, true, true, 'Pau Ferro', 6, 'omni-escala-pau-ferro.png', 'front', '6', NULL, NULL, 29),
(8, 72, true, false, 'Pau Ferro 7', 6, NULL, 'front', '7', NULL, NULL, 50),
(8, 74, true, false, 'Flamed Maple', 6, 'omni-escala-flamed-maple.png', 'front', '6', NULL, NULL, 43),
(8, 747, true, false, 'Flamed Maple', 6, NULL, 'front', '7', NULL, NULL, 69),
(8, 75, false, false, 'Quilted Maple', 6, NULL, 'front', '6', NULL, NULL, 97),
(8, 749, false, false, 'Quilted Maple', 6, NULL, 'front', '7', NULL, NULL, 149),
(8, 76, true, false, 'Pale Moon Ebony', 6, 'omni-escala-pale-moon.png', 'front', '6', NULL, NULL, 157),
(8, 751, true, false, 'Pale Moon Ebony', 6, NULL, 'front', '7', NULL, NULL, 249),
(9, 428, true, false, '12"', NULL, NULL, NULL, 'all', NULL, NULL, 0),
(9, 431, true, false, '14"', NULL, NULL, NULL, 'all', NULL, NULL, 0),
(9, 430, true, true, '16"', NULL, NULL, NULL, 'all', NULL, NULL, 0),
(9, 429, true, false, '20"', NULL, NULL, NULL, 'all', NULL, NULL, 0),
(10, 466, true, false, 'C-Thin', NULL, NULL, NULL, 'all', NULL, NULL, 0),
(10, 467, true, false, 'D', NULL, NULL, NULL, 'all', NULL, NULL, 0),
(11, 440, true, true, 'Carbon fiber reinforcements (2x)', NULL, NULL, NULL, 'all', NULL, NULL, 27),
(12, 393, true, true, 'Graphtech TUSQ', 7, NULL, NULL, 'all', NULL, NULL, 9),
(13, 405, true, true, 'No binding', 10, NULL, 'front', 'all', NULL, NULL, 0),
(13, 24, true, false, 'Binding no headstock and fretboard', 10, NULL, 'front', 'all', NULL, NULL, 44),
(14, 179, true, true, 'Jescar Inox 51100 (Jumbo)', 8, 'omni-braco-trastes-padrao.png', 'front', 'all', NULL, NULL, 31),
(14, 396, true, false, 'Jescar Inox 58118 (Extra Jumbo)', 8, 'omni-braco-trastes-padrao.png', 'front', 'all', NULL, NULL, 31),
(15, 404, true, false, 'No Inlays', NULL, NULL, NULL, 'all', NULL, NULL, 0),
(15, 25, true, true, 'Constellations', NULL, NULL, NULL, 'all', NULL, NULL, 10),
(16, 992, true, false, 'Black', NULL, NULL, NULL, 'all', NULL, NULL, 0),
(16, 1002, true, false, 'White', NULL, NULL, NULL, 'all', NULL, NULL, 0),
(17, 425, true, true, 'Standard', NULL, NULL, NULL, 'all', NULL, NULL, 0),
(17, 426, true, false, 'Fluorescent (Green)', NULL, NULL, NULL, 'all', NULL, NULL, 45),
(18, 456, true, true, 'Matte', NULL, NULL, NULL, 'all', NULL, NULL, 0),
(18, 457, true, false, 'Gloss', NULL, NULL, NULL, 'all', NULL, NULL, 0),
(19, 91, true, true, 'Paulownia', 1, 'omni-corpo-paulownia.png', 'front', 'all', NULL, NULL, 29),
(19, 94, true, false, 'Mahogany', 1, 'omni-corpo-mogno.png', 'front', 'all', NULL, NULL, 49),
(19, 274, true, false, 'Freijó', 1, 'omni-corpo-freijo.png', 'front', 'all', NULL, NULL, 60),
(19, 95, false, false, 'Black Limba', 1, NULL, 'front', 'all', NULL, NULL, 243),
(19, 96, false, false, 'Swamp Ash', 1, NULL, 'front', 'all', NULL, NULL, 265),
(21, 244, true, true, 'Flamed Maple', 2, 'omni-tampo-flamed-maple.png', 'front', 'all', NULL, NULL, 145),
(21, 53, true, false, 'Maple Burl', 2, NULL, 'front', 'all', NULL, NULL, 279),
(21, 54, true, false, 'Golden Camphor', 2, NULL, 'front', 'all', NULL, NULL, 279),
(21, 55, true, false, 'Buckeye Burl', 2, 'omni-tampo-buckeye-burl-natural.png', 'front', 'all', NULL, NULL, 365),
(21, 56, true, false, 'Pale Moon Ebony', 2, NULL, 'front', 'all', NULL, NULL, 408),
(21, 59, true, false, 'Quilted Maple', 2, NULL, 'front', 'all', NULL, NULL, 329),
(21, 61, true, false, 'Crotch Bastogne Walnut', 2, NULL, 'front', 'all', NULL, NULL, 372),
(21, 62, true, false, 'Hybrid (Burl and Resin)', 2, NULL, 'front', 'all', NULL, NULL, 0),
(21, 64, true, false, 'Koa', 2, NULL, 'front', 'all', NULL, NULL, 893),
(21, 65, true, false, 'Mun Ebony', 2, NULL, 'front', 'all', NULL, NULL, 1018),
(21, 66, true, false, 'Crotch Ebony', 2, NULL, 'front', 'all', NULL, NULL, 1352),
(22, 734, true, false, 'Blue', NULL, NULL, NULL, 'all', 'all', NULL, 0),
(22, 735, true, false, 'Natural', NULL, NULL, NULL, 'all', 'all', NULL, 0),
(22, 736, true, false, 'Red', NULL, NULL, NULL, 'all', 'all', NULL, 0),
(22, 737, true, false, 'Yellow', NULL, NULL, NULL, 'all', 'all', NULL, 0),
(22, 738, true, false, 'Purple', NULL, NULL, NULL, 'all', 'all', NULL, 0),
(23, 409, true, false, 'Acrylic', NULL, NULL, 'back', 'all', NULL, NULL, 10),
(23, 408, true, false, 'Wood', NULL, NULL, 'back', 'all', NULL, NULL, 12),
(24, 230, true, true, 'Straight', NULL, NULL, NULL, 'all', NULL, NULL, 0),
(24, 229, true, false, 'Angled (10º)', NULL, NULL, NULL, 'all', NULL, NULL, 133),
(25, 727, true, true, 'Black', NULL, NULL, NULL, 'all', NULL, NULL, 0),
(25, 728, true, false, 'Chrome', NULL, NULL, NULL, 'all', NULL, NULL, 0),
(26, 112, true, true, 'Hipshot Bridge 6', 3, 'omni-ponte-fixa-6-preto.png', 'front', '6', 'Preto', NULL, 110),
(26, 996, true, true, 'Hipshot Bridge 6', 3, 'omni-ponte-fixa-6-cromado.png', 'front', '6', 'Cromado', NULL, 3),
(26, 979, true, true, 'Hipshot Bridge 7', 3, NULL, 'front', '7', 'Preto', NULL, 153),
(26, 115, true, false, 'Schaller Hannes Bridge', 3, NULL, 'front', '6', 'Preto', NULL, 0),
(26, 116, true, false, 'Evertune Bridge 6', 3, NULL, 'front', '6', 'Preto', NULL, 394),
(26, 120, true, false, 'Multiscale Hipshot Bridge 6', 3, NULL, 'front', '6', 'Preto', 'Multiscale', 119),
(26, 122, true, false, 'Multiscale Hipshot Bridge 7', 3, NULL, 'front', '7', 'Preto', 'Multiscale', 192),
(26, 390, true, false, 'Vega-trem 6 Tremolo', 3, NULL, 'front', '6', 'Preto', NULL, 369),
(26, 128, true, false, 'Gotoh 510 6 Tremolo', 3, NULL, 'front', '6', 'Preto', NULL, 84),
(26, 130, true, false, 'Floating Gotoh 6', 3, NULL, 'front', '6', 'Preto', NULL, 197),
(27, 98, true, false, 'Gotoh SG381', 10, NULL, 'front', '6', 'Preto', NULL, 77),
(27, 99, true, false, 'Gotoh SG381 (7-string)', 10, NULL, 'front', '7', 'Preto', NULL, 115),
(27, 102, true, true, 'Hipshot Grip-lock Open', 10, 'omni-tarraxas-6-preto.png', 'front', '6', 'Preto', NULL, 109),
(27, 997, true, true, 'Hipshot Grip-lock Open', 10, 'omni-tarraxas-6-cromado.png', 'front', '6', 'Cromado', NULL, 109),
(27, 104, true, false, 'Hipshot Grip-lock Open 7', 10, NULL, 'front', '7', 'Preto', NULL, 164),
(28, 36, true, false, 'Wooden Tuners (6x)', 10, NULL, 'front', '6', NULL, NULL, 58),
(29, 731, true, true, '1 Volume', 3, 'omni-knob-volume-preto.png', 'front', 'all', 'Preto', NULL, 23),
(29, 732, true, true, '1 Tone', 3, 'omni-knob-tone-preto.png', 'front', 'all', 'Preto', NULL, 23),
(29, 999, true, true, '1 Volume', 3, 'omni-knob-volume-cromado.png', 'front', 'all', 'Cromado', NULL, 23),
(29, 1000, true, true, '1 Tone', 3, 'omni-knob-tone-cromado.png', 'front', 'all', 'Cromado', NULL, 23),
(30, 755, true, false, 'Black', 3, 'captador-humbucker-preto.png', 'front', '6', NULL, NULL, 0),
(30, 756, true, false, 'White', 3, 'captador-humbucker-branco.png', 'front', '6', NULL, NULL, 0),
(30, 147, true, false, 'Fishman Modern 6 (Neck)', NULL, NULL, 'front', '6', NULL, NULL, 152),
(30, 148, true, false, 'Fishman Modern 7 (Neck)', NULL, NULL, 'front', '7', NULL, NULL, 223),
(30, 149, true, false, 'Fishman Modern 7 (Soapbar) (Neck)', NULL, NULL, 'front', '7', NULL, NULL, 215),
(30, 151, true, false, 'Fishman Abasi 6 (Neck)', NULL, NULL, 'front', '6', NULL, NULL, 178),
(30, 152, true, false, 'Fishman Abasi 7 (Neck)', NULL, NULL, 'front', '7', NULL, NULL, 266),
(30, 153, true, false, 'Fishman Abasi 7 (Soapbar) (Neck)', NULL, NULL, 'front', '7', NULL, NULL, 273),
(30, 730, true, false, 'No Pickup', NULL, NULL, 'front', 'all', NULL, NULL, 0),
(31, 658, true, false, 'Fishman Modern 6 (Bridge)', NULL, NULL, 'front', '6', NULL, NULL, 152),
(31, 659, true, false, 'Fishman Modern 7 (Bridge)', NULL, NULL, 'front', '7', NULL, NULL, 223),
(31, 660, true, false, 'Fishman Modern 7 (Soapbar) (Bridge)', NULL, NULL, 'front', '7', NULL, NULL, 215),
(31, 662, true, false, 'Fishman Abasi 6 (Bridge)', NULL, NULL, 'front', '6', NULL, NULL, 178),
(31, 663, true, false, 'Fishman Abasi 7 (Bridge)', NULL, NULL, 'front', '7', NULL, NULL, 266),
(31, 664, true, false, 'Fishman Abasi 7 (Soapbar) (Bridge)', NULL, NULL, 'front', '7', NULL, NULL, 273),
(31, 468, true, false, 'No pickup', NULL, NULL, 'front', '6', NULL, NULL, 0),
(33, 37, true, false, '1.5mm wooden toppers (2x)', 3, NULL, 'front', 'all', NULL, NULL, 24),
(34, 434, true, false, 'Multiscale - Angled Baseplate (Neck)', NULL, NULL, NULL, 'all', 'all', 'Multiscale', 0),
(35, 667, true, false, 'Multiscale - Angled Baseplate (Bridge)', NULL, NULL, NULL, 'all', 'all', 'Multiscale', 0),
(36, 379, true, false, 'Pluria Hard Case', NULL, NULL, NULL, 'all', NULL, NULL, 106),
(30, 498, true, false, 'Bare Knuckle Unity 6 (Neck)', NULL, NULL, 'front', 6, NULL, NULL, 0),
(30, 500, true, false, 'Bare Knuckle Unity 7 (Neck)', NULL, NULL, 'front', 7, NULL, NULL, 0),
(30, 504, true, false, 'Bare Knuckle Holydiver 6 (Neck)', NULL, NULL, 'front', 6, NULL, NULL, 0),
(30, 506, true, false, 'Bare Knuckle Holydiver 7 (Neck)', NULL, NULL, 'front', 7, NULL, NULL, 0),
(30, 511, true, false, 'Bare Knuckle Miracle Man 6 (Neck)', NULL, NULL, 'front', 6, NULL, NULL, 0),
(30, 513, true, false, 'Bare Knuckle Miracle Man 7 (Neck)', NULL, NULL, 'front', 7, NULL, NULL, 0),
(30, 519, true, false, 'Bare Knuckle Warpig 6 (Neck)', NULL, NULL, 'front', 6, NULL, NULL, 0),
(30, 524, true, false, 'Bare Knuckle Nailbomb 6 (Neck)', NULL, NULL, 'front', 6, NULL, NULL, 0),
(30, 526, true, false, 'Bare Knuckle Nailbomb 7 (Neck)', NULL, NULL, 'front', 7, NULL, NULL, 0),
(30, 530, true, false, 'Bare Knuckle Cold Sweat 6 (Neck)', NULL, NULL, 'front', 6, NULL, NULL, 0),
(30, 532, true, false, 'Bare Knuckle Cold Sweat 7 (Neck)', NULL, NULL, 'front', 7, NULL, NULL, 0),
(30, 536, true, false, 'Bare Knuckle Painkiller 6 (Neck)', NULL, NULL, 'front', 6, NULL, NULL, 0),
(30, 538, true, false, 'Bare Knuckle Painkiller 7 (Neck)', NULL, NULL, 'front', 7, NULL, NULL, 0),
(30, 542, true, false, 'Bare Knuckle Aftermath 6 (Neck)', NULL, NULL, 'front', 6, NULL, NULL, 0),
(30, 544, true, false, 'Bare Knuckle Aftermath 7 (Neck)', NULL, NULL, 'front', 7, NULL, NULL, 0),
(30, 548, true, false, 'Bare Knuckle Juggernaut 6 (Neck)', NULL, NULL, 'front', 6, NULL, NULL, 0),
(30, 550, true, false, 'Bare Knuckle Juggernaut 7 (Neck)', NULL, NULL, 'front', 7, NULL, NULL, 0),
(30, 554, true, false, 'Bare Knuckle Ragnarok 6 (Neck)', NULL, NULL, 'front', 6, NULL, NULL, 0),
(30, 556, true, false, 'Bare Knuckle Ragnarok 7 (Neck)', NULL, NULL, 'front', 7, NULL, NULL, 0),
(30, 562, true, false, 'Bare Knuckle Crawler 6 (Neck)', NULL, NULL, 'front', 6, NULL, NULL, 0),
(30, 563, true, false, 'Bare Knuckle Crawler 7 (Neck)', NULL, NULL, 'front', 7, NULL, NULL, 0),
(30, 568, true, false, 'Bare Knuckle Impulse 6 (Neck)', NULL, NULL, 'front', 6, NULL, NULL, 0),
(30, 569, true, false, 'Bare Knuckle Impulse 7 (Neck)', NULL, NULL, 'front', 7, NULL, NULL, 0),
(30, 574, true, false, 'Bare Knuckle Polymath 6 (Neck)', NULL, NULL, 'front', 6, NULL, NULL, 0),
(30, 575, true, false, 'Bare Knuckle Polymath 7 (Neck)', NULL, NULL, 'front', 7, NULL, NULL, 0),
(30, 580, true, false, 'Bare Knuckle Rebel Yell 6 (Neck)', NULL, NULL, 'front', 6, NULL, NULL, 0),
(30, 581, true, false, 'Bare Knuckle Rebel Yell 7 (Neck)', NULL, NULL, 'front', 7, NULL, NULL, 0),
(30, 586, true, false, 'Bare Knuckle Silo 6 (Neck)', NULL, NULL, 'front', 6, NULL, NULL, 0),
(30, 587, true, false, 'Bare Knuckle Silo 7 (Neck)', NULL, NULL, 'front', 7, NULL, NULL, 0),
(30, 589, true, false, 'Bare Knuckle Warpig 7 (Neck)', NULL, NULL, 'front', 7, NULL, NULL, 0),
(30, 591, true, false, 'Bare Knuckle Black Hawk 6 (Neck)', NULL, NULL, 'front', 6, NULL, NULL, 0),
(30, 592, true, false, 'Bare Knuckle Black Hawk 7 (Neck)', NULL, NULL, 'front', 7, NULL, NULL, 0),
(30, 595, true, false, 'Bare Knuckle Stormy Monday 6 (Neck)', NULL, NULL, 'front', 6, NULL, NULL, 0),
(30, 597, true, false, 'Bare Knuckle Stormy Monday 7 (Neck)', NULL, NULL, 'front', 7, NULL, NULL, 0),
(30, 601, true, false, 'Bare Knuckle PG Blues 6 (Neck)', NULL, NULL, 'front', 6, NULL, NULL, 0),
(30, 603, true, false, 'Bare Knuckle PG Blues 7 (Neck)', NULL, NULL, 'front', 7, NULL, NULL, 0),
(30, 607, true, false, 'Bare Knuckle The Mule 6 (Neck)', NULL, NULL, 'front', 6, NULL, NULL, 0),
(30, 609, true, false, 'Bare Knuckle The Mule 7 (Neck)', NULL, NULL, 'front', 7, NULL, NULL, 0),
(30, 613, true, false, 'Bare Knuckle Riff Raff 6 (Neck)', NULL, NULL, 'front', 6, NULL, NULL, 0),
(30, 615, true, false, 'Bare Knuckle Riff Raff 7 (Neck)', NULL, NULL, 'front', 7, NULL, NULL, 0),
(30, 621, true, false, 'Bare Knuckle PolyPaf 6 (Neck)', NULL, NULL, 'front', 6, NULL, NULL, 0),
(30, 622, true, false, 'Bare Knuckle PolyPaf 7 (Neck)', NULL, NULL, 'front', 7, NULL, NULL, 0),
(30, 626, true, false, 'Bare Knuckle Black Dog 6 (Neck)', NULL, NULL, 'front', 6, NULL, NULL, 0),
(30, 628, true, false, 'Bare Knuckle Black Dog 7 (Neck)', NULL, NULL, 'front', 7, NULL, NULL, 0),
(30, 632, true, false, 'Bare Knuckle Emerald 6 (Neck)', NULL, NULL, 'front', 6, NULL, NULL, 0),
(30, 634, true, false, 'Bare Knuckle Emerald 7 (Neck)', NULL, NULL, 'front', 7, NULL, NULL, 0),
(30, 638, true, false, 'Bare Knuckle Abraxas 6 (Neck)', NULL, NULL, 'front', 6, NULL, NULL, 0),
(30, 640, true, false, 'Bare Knuckle Abraxas 7 (Neck)', NULL, NULL, 'front', 7, NULL, NULL, 0),
(30, 646, true, false, 'Bare Knuckle Peacemaker 6 (Neck)', NULL, NULL, 'front', 6, NULL, NULL, 0),
(30, 647, true, false, 'Bare Knuckle Peacemaker 7 (Neck)', NULL, NULL, 'front', 7, NULL, NULL, 0),
(30, 651, true, false, 'Bare Knuckle VHII 6 (Neck)', NULL, NULL, 'front', 6, NULL, NULL, 0),
(30, 652, true, false, 'Bare Knuckle VHII 7 (Neck)', NULL, NULL, 'front', 7, NULL, NULL, 0),
(31, 220, true, false, 'Bare Knuckle 7 Polypaf (Bridge)', NULL, NULL, 'front', 7, NULL, NULL, 0),
(31, 499, true, false, 'Bare Knuckle Unity 7 (Bridge)', NULL, NULL, 'front', 7, NULL, NULL, 0),
(31, 503, true, false, 'Bare Knuckle Holydiver 6 (Bridge)', NULL, NULL, 'front', 6, NULL, NULL, 0),
(31, 505, true, false, 'Bare Knuckle Holydiver 7 (Bridge)', NULL, NULL, 'front', 7, NULL, NULL, 0),
(31, 509, true, false, 'Bare Knuckle Warpig 6 (Bridge)', NULL, NULL, 'front', 6, NULL, NULL, 0),
(31, 510, true, false, 'Bare Knuckle Unity 6 (Bridge)', NULL, NULL, 'front', 6, NULL, NULL, 0),
(31, 512, true, false, 'Bare Knuckle Warpig 7 (Bridge)', NULL, NULL, 'front', 7, NULL, NULL, 0),
(31, 516, true, false, 'Bare Knuckle Miracle Man 6 (Bridge)', NULL, NULL, 'front', 6, NULL, NULL, 0),
(31, 517, true, false, 'Bare Knuckle Miracle Man 7 (Bridge)', NULL, NULL, 'front', 7, NULL, NULL, 0),
(31, 518, true, false, 'Bare Knuckle Miracle Man 8 (Bridge)', NULL, NULL, 'front', 6, NULL, NULL, 0),
(31, 520, true, false, 'Bare Knuckle Black Hawk 7 (Bridge)', NULL, NULL, 'front', 7, NULL, NULL, 0),
(31, 522, true, false, 'Bare Knuckle Black Hawk 6 (Bridge)', NULL, NULL, 'front', 6, NULL, NULL, 0),
(31, 523, true, false, 'Bare Knuckle Nailbomb 6 (Bridge)', NULL, NULL, 'front', 6, NULL, NULL, 0),
(31, 525, true, false, 'Bare Knuckle Nailbomb 7 (Bridge)', NULL, NULL, 'front', 7, NULL, NULL, 0),
(31, 529, true, false, 'Bare Knuckle Cold Sweat 6 (Bridge)', NULL, NULL, 'front', 6, NULL, NULL, 0),
(31, 531, true, false, 'Bare Knuckle Cold Sweat 7 (Bridge)', NULL, NULL, 'front', 7, NULL, NULL, 0),
(31, 535, true, false, 'Bare Knuckle Painkiller 6 (Bridge)', NULL, NULL, 'front', 6, NULL, NULL, 0),
(31, 537, true, false, 'Bare Knuckle Painkiller 7 (Bridge)', NULL, NULL, 'front', 7, NULL, NULL, 0),
(31, 541, true, false, 'Bare Knuckle Aftermath 6 (Bridge)', NULL, NULL, 'front', 6, NULL, NULL, 0),
(31, 543, true, false, 'Bare Knuckle Aftermath 7 (Bridge)', NULL, NULL, 'front', 7, NULL, NULL, 0),
(31, 547, true, false, 'Bare Knuckle Juggernaut 6 (Bridge)', NULL, NULL, 'front', 6, NULL, NULL, 0),
(31, 549, true, false, 'Bare Knuckle Juggernaut 7 (Bridge)', NULL, NULL, 'front', 7, NULL, NULL, 0),
(31, 553, true, false, 'Bare Knuckle Ragnarok 6 (Bridge)', NULL, NULL, 'front', 6, NULL, NULL, 0),
(31, 555, true, false, 'Bare Knuckle Ragnarok 7 (Bridge)', NULL, NULL, 'front', 7, NULL, NULL, 0),
(31, 559, true, false, 'Bare Knuckle Crawler 6 (Bridge)', NULL, NULL, 'front', 6, NULL, NULL, 0),
(31, 560, true, false, 'Bare Knuckle Crawler 7 (Bridge)', NULL, NULL, 'front', 7, NULL, NULL, 0),
(31, 565, true, false, 'Bare Knuckle Impulse 6 (Bridge)', NULL, NULL, 'front', 6, NULL, NULL, 0),
(31, 566, true, false, 'Bare Knuckle Impulse 7 (Bridge)', NULL, NULL, 'front', 7, NULL, NULL, 0),
(31, 571, true, false, 'Bare Knuckle Polymath 6 (Bridge)', NULL, NULL, 'front', 6, NULL, NULL, 0),
(31, 572, true, false, 'Bare Knuckle Polymath 7 (Bridge)', NULL, NULL, 'front', 7, NULL, NULL, 0),
(31, 577, true, false, 'Bare Knuckle Rebel Yell 6 (Bridge)', NULL, NULL, 'front', 6, NULL, NULL, 0),
(31, 578, true, false, 'Bare Knuckle Rebel Yell 7 (Bridge)', NULL, NULL, 'front', 7, NULL, NULL, 0),
(31, 583, true, false, 'Bare Knuckle Silo 6 (Bridge)', NULL, NULL, 'front', 6, NULL, NULL, 0),
(31, 584, true, false, 'Bare Knuckle Silo 7 (Bridge)', NULL, NULL, 'front', 7, NULL, NULL, 0),
(31, 594, true, false, 'Bare Knuckle Stormy Monday 6 (Bridge)', NULL, NULL, 'front', 6, NULL, NULL, 0),
(31, 596, true, false, 'Bare Knuckle Stormy Monday 7 (Bridge)', NULL, NULL, 'front', 7, NULL, NULL, 0),
(31, 600, true, false, 'Bare Knuckle PG Blues 6 (Bridge)', NULL, NULL, 'front', 6, NULL, NULL, 0),
(31, 602, true, false, 'Bare Knuckle PG Blues 7 (Bridge)', NULL, NULL, 'front', 7, NULL, NULL, 0),
(31, 606, true, false, 'Bare Knuckle The Mule 6 (Bridge)', NULL, NULL, 'front', 6, NULL, NULL, 0),
(31, 608, true, false, 'Bare Knuckle The Mule 7 (Bridge)', NULL, NULL, 'front', 7, NULL, NULL, 0),
(31, 612, true, false, 'Bare Knuckle Riff Raff 6 (Bridge)', NULL, NULL, 'front', 6, NULL, NULL, 0),
(31, 614, true, false, 'Bare Knuckle Riff Raff 7 (Bridge)', NULL, NULL, 'front', 7, NULL, NULL, 0),
(31, 618, true, false, 'Bare Knuckle PolyPaf 6 (Bridge)', NULL, NULL, 'front', 6, NULL, NULL, 0),
(31, 619, true, false, 'Bare Knuckle PolyPaf 7 (Bridge)', NULL, NULL, 'front', 7, NULL, NULL, 0),
(31, 624, true, false, 'Bare Knuckle VHII 6 (Bridge)', NULL, NULL, 'front', 6, NULL, NULL, 0),
(31, 625, true, false, 'Bare Knuckle Black Dog 6 (Bridge)', NULL, NULL, 'front', 6, NULL, NULL, 0),
(31, 627, true, false, 'Bare Knuckle Black Dog 7 (Bridge)', NULL, NULL, 'front', 7, NULL, NULL, 0),
(31, 631, true, false, 'Bare Knuckle Emerald 6 (Bridge)', NULL, NULL, 'front', 6, NULL, NULL, 0),
(31, 633, true, false, 'Bare Knuckle Emerald 7 (Bridge)', NULL, NULL, 'front', 7, NULL, NULL, 0),
(31, 637, true, false, 'Bare Knuckle Abraxas 6 (Bridge)', NULL, NULL, 'front', 6, NULL, NULL, 0),
(31, 639, true, false, 'Bare Knuckle Abraxas 7 (Bridge)', NULL, NULL, 'front', 7, NULL, NULL, 0),
(31, 643, true, false, 'Bare Knuckle Peacemaker 6 (Bridge)', NULL, NULL, 'front', 6, NULL, NULL, 0),
(31, 644, true, false, 'Bare Knuckle Peacemaker 7 (Bridge)', NULL, NULL, 'front', 7, NULL, NULL, 0),
(31, 649, true, false, 'Bare Knuckle VHII 7 (Bridge)', NULL, NULL, 'front', 7, NULL, NULL, 0);