// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://flzxuupunfdzgjjhkhuj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZsenh1dXB1bmZkemdqamhraHVqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc5MzgxODUsImV4cCI6MjA1MzUxNDE4NX0.J85kRU3QThLaDpNRvGfAvK3kbvKENjXsPxcbiE2gh5M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);